name: Deploy to EC2 with Docker

on:
  push:
    branches: ["main"]   # change to "master" if your repo uses master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to project folder; clone if it doesn't exist
          if [ ! -d "Time_manager_full" ]; then
            git clone https://github.com/timemanagerepitech/Time_manager_full.git
          fi
          cd Time_manager_full
          
          # Pull latest changes
          git pull origin main
          
          # Stop and rebuild Docker containers
          docker-compose down
          docker-compose up -d --build
          
          # Optional: Clean up old Docker images to save space
          docker image prune -af
          EOF
